name: Professions
main: git.doomshade.professions.Professions
author: Doomshade
version: 1.1
description: Best plugin EU
depend: [GUIApi, ProtocolLib]
softdepend: [Citizens, Vault, PermissionsEx, SkillAPI, Sinister_LoreAttributes]

commands:
  prof:
    description: default cmd
  prof-mining:
    description: mining cmd
  prof-herbalism:
    description: herbalism cmd
  prof-alchemy:
    description: alchemy cmd